# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='students',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
