# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_auto_20180110_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
