# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_students_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='lastname',
        ),
    ]
